language: python
python:
  - "3.6"

install:
  - pip install coveralls flake8 mypy
  - pip install .

script: 
  - flake8 nsw_fuel nsw_fuel_tests
  - mypy --strict nsw_fuel nsw_fuel_tests
  - coverage run --source=nsw_fuel setup.py test

after_success: coveralls

before_deploy:
  - git describe --dirty --always > VERSION

deploy:
  provider: pypi
  user: nickw444-deploy
  password: "$PYPI_PASSWORD"
  on: 
    tags: true
