language: python
python:
  - "3.6"
  - "3.7"

install:
  - pip install coveralls flake8
  - pip install .

script: 
  - flake8 .
  - coverage run --source=nsw_fuel setup.py test

after_success: coveralls

before_deploy:
  - git describe --dirty --always > VERSION

deploy:
  provider: pypi
  user: nickw444-deploy
  password: "$PYPI_PASSWORD"
  on: 
    tags: true
